<a href="https://colab.research.google.com/github/AbdelrahmanFeteha/DataSci-PreProcessing/blob/main/DS_Day4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
units_sold = [50,80,60]
cost_per_unit = [10,12,9]
sales_price_per_unit = [15,18,12]

units_sold_df = pd.DataFrame(units_sold)
cost_per_unit_df = pd.DataFrame(cost_per_unit)
sales_price_per_unit_df = pd.DataFrame(sales_price_per_unit)

#make them all one dataframe
merged_df = pd.concat([units_sold_df, cost_per_unit_df, sales_price_per_unit_df], axis=1)

merged_df

total_profit = (sales_price_per_unit_df - cost_per_unit_df) * units_sold_df
total_profit = pd.DataFrame(total_profit)
merged_df = pd.concat([merged_df, total_profit], axis=1)
merged_df

#add column names
merged_df.columns = ['units_sold', 'cost_per_unit', 'sales_price_per_unit', 'total_profit']
merged_df

units_sold  cost_per_unit  sales_price_per_unit  total_profit
0          50             10                    15           250
1          80             12                    18           480
2          60              9                    12           180

## Log transformation


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = {
    'Feature': [1,10,100,1000,10000]
}

df = pd.DataFrame(data)

#log tranformation
df['Log Feature'] = np.log10(df['Feature'])
df

Feature  Log Feature
0        1          0.0
1       10          1.0
2      100          2.0
3     1000          3.0
4    10000          4.0

## Min Max Scaler

In [ ]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import pandas as pd

In [ ]:
#sample datased
data = {
    'Feature' : [1,2,3,4,5]
}
df = pd.DataFrame(data)
df

Feature
0        1
1        2
2        3
3        4
4        5

In [ ]:
#min max scaling
scaler = MinMaxScaler()
df_scaled = scaler.fit_transform(df)
print("Min max scaled ata: \n", df_scaled)

Min max scaled ata: 
 [[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]


In [ ]:
#Standardization
scaler=StandardScaler()
df_standardized = scaler.fit_transform(df)
print("Standardized Data:\n", df_standardized)

Standardized Data:
 [[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


## Binning

In [ ]:
data = {'Age' : [18,25,47,51,62]}
df = pd.DataFrame(data)

bins = [0,18,35,50,100]
labels = ['Youth', 'Young Adult', 'Adult', 'Senior']
df['Age_Group'] = pd.cut(df['Age'], bins=bins, labels=labels)
df

Age    Age_Group
0   18        Youth
1   25  Young Adult
2   47        Adult
3   51       Senior
4   62       Senior

One Hot Encoding

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Sample data
data = np.array([['cat'], ['dog'], ['cat'], ['bird']])
data = np.array([['bird '], ['cat'], ['dog'], ['cat']])


# Initialize encoder
encoder = OneHotEncoder(sparse_output=False)

# Fit and transform the data
encoded_data = encoder.fit_transform(data)

print("Original Data: ")
print(data)

print("\nOne-Hot Encoded Data: ")
print(encoded_data)


Original Data: 
[['bird ']
 ['cat']
 ['dog']
 ['cat']]

One-Hot Encoded Data: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


## Task 1

###Load the data

In [ ]:
data = {
    'Age' : [22,25,47,51,62],
    'Salary' : [20000,25000,47000,51000,62000],
    'City' : ['New York', 'Los Angeles', 'Chicago', 'New York', 'Chicago']
}

df = pd.DataFrame(data)
df

Age  Salary         City
0   22   20000     New York
1   25   25000  Los Angeles
2   47   47000      Chicago
3   51   51000     New York
4   62   62000      Chicago

### Feature Engineering

In [ ]:
##create a new fature age salary ratio (age / salary)
df['Age_Salary_Ratio'] = df['Age'] / df ['Salary']
df

Age  Salary         City  Age_Salary_Ratio
0   22   20000     New York            0.0011
1   25   25000  Los Angeles            0.0010
2   47   47000      Chicago            0.0010
3   51   51000     New York            0.0010
4   62   62000      Chicago            0.0010

### Min Max Scaling

In [ ]:
##min max scaling for salary
scaler = MinMaxScaler()
# Initialize the MinMaxScaler
scaler = MinMaxScaler()

#min max
df['Salary_Scaled'] = scaler.fit_transform(df[['Salary']])

#Faster method:
#columns_to_scale = ['Salary', 'Age',]
#f[columns_to_scale] = scaler.fit_transform(df[columns_to_scale])

# Print the scaled data
print("Min-Max Scaled data:\n", df)

Min-Max Scaled data:
    Age  Salary         City  Age_Salary_Ratio  Salary_Scaled
0   22   20000     New York            0.0011       0.000000
1   25   25000  Los Angeles            0.0010       0.119048
2   47   47000      Chicago            0.0010       0.642857
3   51   51000     New York            0.0010       0.738095
4   62   62000      Chicago            0.0010       1.000000


### One Hot Encoding

In [ ]:
##Handle categorical variables

# Initialize OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)

encoded_cities = encoder.fit_transform(df[['City']])

# Convert the encoded cities into a DataFrame
encoded_df = pd.DataFrame(encoded_cities, columns=encoder.get_feature_names_out(['City']))

# Concatenate the original DataFrame with the encoded DataFrame
df = pd.concat([df, encoded_df], axis=1)
df

Age  Salary         City  Age_Salary_Ratio  Salary_Scaled  City_Chicago  \
0   22   20000     New York            0.0011       0.000000           0.0   
1   25   25000  Los Angeles            0.0010       0.119048           0.0   
2   47   47000      Chicago            0.0010       0.642857           1.0   
3   51   51000     New York            0.0010       0.738095           0.0   
4   62   62000      Chicago            0.0010       1.000000           1.0   

   City_Los Angeles  City_New York  
0               0.0            1.0  
1               1.0            0.0  
2               0.0            0.0  
3               0.0            1.0  
4               0.0            0.0

### Dropping unecessary columns

In [ ]:
# Correctly dropping the unnecessary columns
df.drop(['Salary', 'City'], inplace=True, axis=1)

df

Age  Age_Salary_Ratio  Salary_Scaled  City_Chicago  City_Los Angeles  \
0   22            0.0011       0.000000           0.0               0.0   
1   25            0.0010       0.119048           0.0               1.0   
2   47            0.0010       0.642857           1.0               0.0   
3   51            0.0010       0.738095           0.0               0.0   
4   62            0.0010       1.000000           1.0               0.0   

   City_New York  
0            1.0  
1            0.0  
2            0.0  
3            1.0  
4            0.0

### Trying Binary Encoding

In [ ]:
# Binary Encoding for 'City'
import category_encoders as ce

data = {
    'Age' : [22,25,47,51,62],
    'Salary' : [20000,25000,47000,51000,62000],
    'City' : ['New York', 'Los Angeles', 'Chicago', 'New York', 'Chicago']
}

df = pd.DataFrame(data)

encoder = ce.BinaryEncoder(cols=['City'])
df_encoded = encoder.fit_transform(df)

# Print the DataFrame with scaled and encoded data
print("Processed DataFrame:\n", df_encoded)

Processed DataFrame:
    Age  Salary  City_0  City_1
0   22   20000       0       1
1   25   25000       1       0
2   47   47000       1       1
3   51   51000       0       1
4   62   62000       1       1


In [ ]:
pip install category_encoders


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.9/81.9 kB 5.1 MB/s eta 0:00:00
